variables:
  GIT_SSL_NO_VERIFY: "1"

build_image:
  stage: .pre
  tags: 
    - maven
  script:
    - docker build --build-arg BASE_IMAGE=git-registry.stable.innovation.insee.eu/innovation/rstudio --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

bookdown:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build
  script:
    - Rscript -e "bookdown::render_book('index.Rmd')"
  artifacts:
    paths:
      - _book

pages:
  stage: deploy
  script:
    - mv _book public
  artifacts:
    paths:
      - public
  only:
    - master
