image: gitlab/dind
# image: rocker/geospatial

services:
  - docker:dind
  
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  SHARED_PATH: /builds/shared/$CI_PROJECT_PATH

stages:
  - install
  - deploy

#before_script:
#   - Rscript -e "remotes::install_deps('.', dependencies = TRUE, upgrade = FALSE)"

build_image:
  stage: install
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mkdir -p ${SHARED_PATH}
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE


pages:
  stage: deploy
  image: $CONTAINER_TEST_IMAGE
  script:
    - Rscript -e "install.packages(c('import', 'questionr', 'available'))"
    - Rscript -e "bookdown::render_book('./index.Rmd', output_dir = 'public')"
  artifacts:
    paths:
      - public
  only:
    - master



buildbookdown:
  stage: deploy
  image: $CONTAINER_TEST_IMAGE
  script:
    - Rscript -e "install.packages(c('import', 'questionr', 'available'))"
    - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  artifacts:
    paths:
      - _book
    when: always
