variables:
  GIT_SSL_NO_VERIFY: "1"


before_script:
  - Rscript -e "devtools::install_deps(dependencies = TRUE)"

article:
  stage: deploy
  image: git-registry.stable.innovation.insee.eu/innovation/rstudio
  script:
    - Rscript ./build.R
  artifacts:
    paths:
      - html
    when: always
  only:
      - master


pages:
  stage: deploy
  image: git-registry.stable.innovation.insee.eu/innovation/rstudio
  script:
  - Rscript -e "install.packages('webshot')"
  - Rscript -e "webshot::install_phantomjs()"
  - Rscript -e "bookdown::render_book('./index.Rmd' ,output_dir = 'public')"
  artifacts:
    paths:
      - public
    when: always
  only:
      - bookdown
  