article:
  stage: deploy
  image: rocker/verse:3.5.1
  script:
    - Rscript -e "devtools::install_deps(dependencies = TRUE)"
    - Rscript ./build.R
  artifacts:
    paths:
      - html
    when: always
